### ISSUE TITLE
Lead time for change not working- committime exporter no finding missing required data.

### ISSUE THREAD

**Issue by varodrig** [konveyor/pelorus#271]
We verified that this is a bug. Confirmed by Francisco Meneses. He already has a fix for this. We tested and starting working.

Log information:

04-08-2021 17:36:21 DEBUG    sha: ff48aac7a96d9336ff10726693b7f172e420364c, commit_timestamp not found in cache, executing API call.
04-08-2021 17:36:21 WARNING  Build basic-nginx-build/basic-nginx-41 in app basic-nginx is missing required attributes to collect data. Skipping.
04-08-2021 17:36:21 DEBUG    argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/opt/app-root/src/committime/collector_base.py", line 150, in get_metric_from_build
    metric = self.get_commit_time(metric)
  File "/opt/app-root/src/committime/collector_github.py", line 26, in get_commit_time
    if "gitlab" in git_server or "bitbucket" in git_server:
TypeError: argument of type 'NoneType' is not iterable
04-08-2021 17:36:21 DEBUG    sha: ff48aac7a96d9336ff10726693b7f172e420364c, commit_timestamp not found in cache, executing API call.
04-08-2021 17:36:21 WARNING  Build basic-nginx-build/basic-nginx-42 in app basic-nginx is missing required attributes to collect data. Skipping.
04-08-2021 17:36:21 DEBUG    argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/opt/app-root/src/committime/collector_base.py", line 150, in get_metric_from_build
    metric = self.get_commit_time(metric)
  File "/opt/app-root/src/committime/collector_github.py", line 26, in get_commit_time
    if "gitlab" in git_server or "bitbucket" in git_server:
TypeError: argument of type 'NoneType' is not iterable

**Comment by varodrig** [comment]
It was fixed with PR #264
