### ISSUE TITLE
Unable to view  Lead Time for Change & Change Failure Rate in Grafana

### ISSUE THREAD

**Issue by metaversed** [konveyor/pelorus#339]
Below is logs from committime-exporter
```
01-24-2022 12:32:08 WARNING  Build basic-nginx-build/basic-nginx-9 in app basic-nginx is missing required attributes to collect data. Skipping.
01-24-2022 12:32:08 DEBUG    can only concatenate str (not "NoneType") to str
Traceback (most recent call last):
  File "/opt/app-root/src/committime/collector_base.py", line 232, in get_metric_from_build
    metric = self.get_commit_time(metric)
  File "/opt/app-root/src/committime/collector_github.py", line 30, in get_commit_time
    url = self._prefix + metric.repo_group + "/" + metric.repo_project + self._suffix + metric.commit_hash
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by metaversed** [comment]
@KevinMGranger Any ideas what could be causing this ?

**Comment by etsauer** [comment]
* What version of OpenShift are you on?
* What version of the Pelorus code are you on (what branch/tag)?
* Can you share your values.yaml that you used to configure the exporters?

**Comment by mpryc** [comment]
I am closing this issue.

We had number of changes in the code to calculate the commit time and because this issue is without response from the original author. I am going to close it.
