### ISSUE TITLE
Commit time exporter should not throw error in the logs when no sha is found.

### ISSUE THREAD

**Issue by mpryc** [konveyor/pelorus#514]
If no commit sha is provided via build nor from annotations, ugly traceback is shown in the logs instead of warning message:

```
06-22-2022 14:47:25 DEBUG    /home/migi/Development/Konveyor/Pelorus/pelorus-mpryc/exporters/committime/collector_base.py:193 get_metrics_from_apps() Adding metric for app python-binary-build1
06-22-2022 14:47:25 DEBUG    /home/migi/Development/Konveyor/Pelorus/pelorus-mpryc/exporters/committime/collector_base.py:182 get_metrics_from_apps() Repo URL for app python-binary-build11 is currently None
06-22-2022 14:47:25 DEBUG    /home/migi/Development/Konveyor/Pelorus/pelorus-mpryc/exporters/committime/__init__.py:100 __parse_repourl() repo url = None
06-22-2022 14:47:25 DEBUG    /home/migi/Development/Konveyor/Pelorus/pelorus-mpryc/exporters/committime/collector_base.py:341 _set_commit_timestamp() sha: None, commit_timestamp not found in cache, executing API call.
06-22-2022 14:47:25 ERROR    Error encountered while getting CommitMetric info:
06-22-2022 14:47:25 ERROR    argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/home/migi/Development/Konveyor/Pelorus/pelorus-mpryc/exporters/committime/collector_base.py", line 214, in get_metric_from_build
    metric = self._set_commit_timestamp(metric, errors)
  File "/home/migi/Development/Konveyor/Pelorus/pelorus-mpryc/exporters/committime/collector_base.py", line 345, in _set_commit_timestamp
    metric = self.get_commit_time(metric)
  File "/home/migi/Development/Konveyor/Pelorus/pelorus-mpryc/exporters/committime/collector_github.py", line 48, in get_commit_time
    if "gitlab" in git_server or "bitbucket" in git_server:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by KevinMGranger** [comment]
Fixed with #515.
