### ISSUE TITLE
committime: provider:gitlab; errant message and traceback

### ISSUE THREAD

**Issue by weshayutin** [konveyor/pelorus#577]
* Configure the committime exporters for gitlab.
* Unset the `NAMESPACES` variable
* Ensure LOG_LEVEL=debug

```
07-21-2022 10:00:42 DEBUG    /home/whayutin/OPENSHIFT/git/KONVEYOR/PELORUS/upstream/pelorus/exporters/committime/collector_base.py:343 _set_commit_timestamp() sha: 1b547fd4f4fc557d2e52c9c9a1a87a7d640fa672, commit_timestamp not found in cache, executing API call.
07-21-2022 10:00:42 WARNING  Skipping non GitLab server, found https://github.com
07-21-2022 10:00:42 WARNING  Build pelorus/failure-exporter-1 in app failure-exporter is missing required attributes to collect data. Skipping.
07-21-2022 10:00:42 DEBUG    /home/whayutin/OPENSHIFT/git/KONVEYOR/PELORUS/upstream/pelorus/exporters/committime/collector_base.py:234 get_metric_from_build() 'NoneType' object has no attribute 'commit_time'
Traceback (most recent call last):
  File "/home/whayutin/OPENSHIFT/git/KONVEYOR/PELORUS/upstream/pelorus/exporters/committime/collector_base.py", line 214, in get_metric_from_build
    metric = self._set_commit_timestamp(metric, errors)
  File "/home/whayutin/OPENSHIFT/git/KONVEYOR/PELORUS/upstream/pelorus/exporters/committime/collector_base.py", line 349, in _set_commit_timestamp
    if metric.commit_time is None:
AttributeError: 'NoneType' object has no attribute 'commit_time'
07-21-2022 10:00:42 INFO     Collected commit_timestamp{ namespace=mongo-persistent, app=todolist, commit=baed827995b0e915f1b8759ab88b2bea668a4b7a, image_sha=sha256:e4669362c17758830f53eecb76270f67c3770733363c1acf16df086c35ddd291 } 1658146992.0
```

Now, set the NAMESPACES variable... and you'll see no error
```
(.venv) [whayutin@thinkdoe pelorus]$ export NAMESPACES=mongo-persistent
(.venv) [whayutin@thinkdoe pelorus]$ date +"%T. %3N"; python exporters/committime/app.py;  
10:03:09. 152
/home/whayutin/OPENSHIFT/git/KONVEYOR/PELORUS/upstream/pelorus/exporters/committime/app.py:4: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.util import strtobool
Running committime exporter. No version information found.
Initializing Logger with LogLevel: DEBUG
07-21-2022 10:03:09 ERROR    load cache error: ResourceList.__init__() got an unexpected keyword argument 'base_resource_lookup'
/home/whayutin/OPENSHIFT/git/KONVEYOR/PELORUS/upstream/pelorus/.venv/lib64/python3.10/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.cluster-wdh07052022a.wdh07052022a.mg.dog8code.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/home/whayutin/OPENSHIFT/git/KONVEYOR/PELORUS/upstream/pelorus/.venv/lib64/python3.10/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.cluster-wdh07052022a.wdh07052022a.mg.dog8code.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/home/whayutin/OPENSHIFT/git/KONVEYOR/PELORUS/upstream/pelorus/.venv/lib64/python3.10/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.cluster-wdh07052022a.wdh07052022a.mg.dog8code.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
07-21-2022 10:03:09 INFO     =====Using GitLab Collector=====
07-21-2022 10:03:09 INFO     Watching namespaces: ['mongo-persistent']
07-21-2022 10:03:09 DEBUG    /home/whayutin/OPENSHIFT/git/KONVEYOR/PELORUS/upstream/pelorus/exporters/committime/collector_base.py:122 generate_metrics() Searching for builds with label: app.kubernetes.io/name in namespace: mongo-persistent
/home/whayutin/OPENSHIFT/git/KONVEYOR/PELORUS/upstream/pelorus/.venv/lib64/python3.10/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.cluster-wdh07052022a.wdh07052022a.mg.dog8code.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/home/whayutin/OPENSHIFT/git/KONVEYOR/PELORUS/upstream/pelorus/.venv/lib64/python3.10/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.cluster-wdh07052022a.wdh07052022a.mg.dog8code.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
07-21-2022 10:03:10 DEBUG    /home/whayutin/OPENSHIFT/git/KONVEYOR/PELORUS/upstream/pelorus/exporters/committime/collector_base.py:182 get_metrics_from_apps() Repo URL for app todolist is currently None
07-21-2022 10:03:10 DEBUG    /home/whayutin/OPENSHIFT/git/KONVEYOR/PELORUS/upstream/pelorus/exporters/committime/__init__.py:100 __parse_repourl() repo url = https://gitlab.com/hayutin/mig-demo-apps.git
07-21-2022 10:03:10 DEBUG    /home/whayutin/OPENSHIFT/git/KONVEYOR/PELORUS/upstream/pelorus/exporters/committime/__init__.py:104 __parse_repourl() Parsed: Parsed(pathname='/hayutin/mig-demo-apps.git', protocols=['https'], protocol='https', href='https://gitlab.com/hayutin/mig-demo-apps.git', resource='gitlab.com', user=None, port=None, name='mig-demo-apps', owner='hayutin')
07-21-2022 10:03:10 DEBUG    /home/whayutin/OPENSHIFT/git/KONVEYOR/PELORUS/upstream/pelorus/exporters/committime/collector_base.py:272 _set_repo_url() Repo URL for build todolist-1 provided by 'spec.source.git.uri': https://gitlab.com/hayutin/mig-demo-apps.git
07-21-2022 10:03:10 DEBUG    /home/whayutin/OPENSHIFT/git/KONVEYOR/PELORUS/upstream/pelorus/exporters/committime/collector_base.py:343 _set_commit_timestamp() sha: baed827995b0e915f1b8759ab88b2bea668a4b7a, commit_timestamp not found in cache, executing API call.
07-21-2022 10:03:10 DEBUG    /home/whayutin/OPENSHIFT/git/KONVEYOR/PELORUS/upstream/pelorus/exporters/committime/collector_gitlab.py:54 _connect_to_gitlab() Connecting to GitLab server using token: https://gitlab.com
07-21-2022 10:03:10 DEBUG    /home/whayutin/OPENSHIFT/git/KONVEYOR/PELORUS/upstream/pelorus/exporters/committime/collector_gitlab.py:84 get_commit_time() Getting project: hayutin/mig-demo-apps
07-21-2022 10:03:12 DEBUG    /home/whayutin/OPENSHIFT/git/KONVEYOR/PELORUS/upstream/pelorus/exporters/committime/collector_base.py:193 get_metrics_from_apps() Adding metric for app todolist
07-21-2022 10:03:12 INFO     Collected commit_timestamp{ namespace=mongo-persistent, app=todolist, commit=baed827995b0e915f1b8759ab88b2bea668a4b7a, image_sha=sha256:e4669362c17758830f53eecb76270f67c3770733363c1acf16df086c35ddd291 } 1658146992.0
```

NOTE the ERRORS:
* 07-21-2022 10:00:42 WARNING  Skipping non GitLab server, found https://github.com
* this
```
get_metric_from_build() 'NoneType' object has no attribute 'commit_time'
Traceback (most recent call last):
  File "/home/whayutin/OPENSHIFT/git/KONVEYOR/PELORUS/upstream/pelorus/exporters/committime/collector_base.py", line 214, in get_metric_from_build
    metric = self._set_commit_timestamp(metric, errors)
  File "/home/whayutin/OPENSHIFT/git/KONVEYOR/PELORUS/upstream/pelorus/exporters/committime/collector_base.py", line 349, in _set_commit_timestamp
    if metric.commit_time is None:
AttributeError: 'NoneType' object has no attribute 'commit_time'
```

**Comment by weshayutin** [comment]
issue exists on HEAD, and is NOT related #574
