### ISSUE TITLE
Bitbucket committime exporter is failing to correctly get repo fqdn

### ISSUE THREAD

**Issue by mpryc** [konveyor/pelorus#589]
While running tests against bitbucket committime exporter:

build_uri="https://bitbucket.org/michalpryc/pelorus-bitbucket/"
build_hash="e2c4ef00468dfc10aad1bd2d4c9d470160a7f471"

However bitbucket is failing:
```
08-03-2022 12:19:42 ERROR    Error encountered while getting CommitMetric info:
08-03-2022 12:19:42 ERROR    No connection adapters were found for 'ssh://pelorus-bitbucket/api/2.0/repositories/None/None/commit/e2c4ef00468dfc10aad1bd2d4c9d470160a7f471'
Traceback (most recent call last):
  File "/home/migi/Development/Konveyor/Pelorus/pelorus-minio/exporters/committime/collector_base.py", line 215, in get_metric_from_build
    metric = self._set_commit_timestamp(metric, errors)
  File "/home/migi/Development/Konveyor/Pelorus/pelorus-minio/exporters/committime/collector_base.py", line 348, in _set_commit_timestamp
    metric = self.get_commit_time(metric)
  File "/home/migi/Development/Konveyor/Pelorus/pelorus-minio/exporters/committime/collector_bitbucket.py", line 58, in get_commit_time
    api_dict = self.get_commit_information(
  File "/home/migi/Development/Konveyor/Pelorus/pelorus-minio/exporters/committime/collector_bitbucket.py", line 111, in get_commit_information
    response = self.__session.get(url)
  File "/home/migi/Development/Konveyor/Pelorus/pelorus-minio/.venv/lib64/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/home/migi/Development/Konveyor/Pelorus/pelorus-minio/.venv/lib64/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/migi/Development/Konveyor/Pelorus/pelorus-minio/.venv/lib64/python3.10/site-packages/requests/sessions.py", line 695, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/migi/Development/Konveyor/Pelorus/pelorus-minio/.venv/lib64/python3.10/site-packages/requests/sessions.py", line 792, in get_adapter
    raise InvalidSchema(f"No connection adapters were found for {url!r}")
requests.exceptions.InvalidSchema: No connection adapters were found for 'ssh://pelorus-bitbucket/api/2.0/repositories/None/None/commit/e2c4ef00468dfc10aad1bd2d4c9d470160a7f471'
^CTraceback (most recent call last):
  File "/home/migi/Development/Konveyor/Pelorus/pelorus-minio/exporters/committime/app.py", line 81, in <module>
    time.sleep(1)
```

Checking annotations:

```
$ oc describe -n bitbucket-binary build bitbucket-binary-1
Name:		bitbucket-binary-1
Namespace:	bitbucket-binary
Created:	2 minutes ago
Labels:		app.kubernetes.io/name=bitbucket-binary
		build=bitbucket-binary
		buildconfig=bitbucket-binary
		openshift.io/build-config.name=bitbucket-binary
		openshift.io/build.start-policy=Serial
Annotations:	io.openshift.build.commit.id=e2c4ef00468dfc10aad1bd2d4c9d470160a7f471
		io.openshift.build.source-location=https://bitbucket.org/michalpryc/pelorus-bitbucket/
		openshift.io/build-config.name=bitbucket-binary
		openshift.io/build.number=1
		openshift.io/build.pod-name=bitbucket-binary-1-build
[...]
```

And the metric object:

```
CommitMetric(name='bitbucket-binary', annotations={'io.openshift.build.commit.id': 'e2c4ef00468dfc10aad1bd2d4c9d470160a7f471', 'io.openshift.build.source-location': 'https://bitbucket.org/michalpryc/pelorus-bitbucket/', 'openshift.io/build-config.name': 'bitbucket-binary', 'openshift.io/build.number': '1', 'openshift.io/build.pod-name': 'bitbucket-binary-1-build'}, labels={'app.kubernetes.io/name': 'bitbucket-binary', 'build': 'bitbucket-binary', 'buildconfig': 'bitbucket-binary', 'openshift.io/build-config.name': 'bitbucket-binary', 'openshift.io/build.start-policy': 'Serial'}, namespace='bitbucket-binary', _CommitMetric__repo_url='https://bitbucket.org/michalpryc/pelorus-bitbucket/', _CommitMetric__repo_protocol='ssh', _CommitMetric__repo_fqdn='pelorus-bitbucket', _CommitMetric__repo_group=None, _CommitMetric__repo_name=None, _CommitMetric__repo_project=None, committer=None, commit_hash='e2c4ef00468dfc10aad1bd2d4c9d470160a7f471', commit_time=None, commit_timestamp=None, build_name='bitbucket-binary-1', build_config_name='bitbucket-binary', image_location='image-registry.openshift-image-registry.svc:5000/bitbucket-binary/bitbucket-binary:latest', image_name=None, image_tag=None, image_hash='sha256:55daa4fbd33a03e190c4cf09c3836186df084d4a287aae869f14cdd11992527a')
```

We can see that repo_url is ok, however repo_fqdn and repo_protocol are wrong.

**Comment by mpryc** [comment]
This is exactly the same as #590, fixing #590 causes bitbucket to work properly:

```
08-03-2022 13:49:17 DEBUG    /home/migi/Development/Konveyor/Pelorus/pelorus-minio/exporters/committime/collector_bitbucket.py:126 get_commit_information() For project pelorus-bitbucket, repo https://bitbucket.org/michalpryc/pelorus-bitbucket, build bitbucket-binary-1, commit e2c4ef00468dfc10aad1bd2d4c9d470160a7f471 BitBucket returned {"type": "commit", "hash": "e2c4ef00468dfc10aad1bd2d4c9d470160a7f471", "date": "2022-07-14T13:46:54+00:00", "author": {"type": "author", "raw": "Michal Pryc <mpryc@redhat.com>", "user": {"display_name": "Michal Pryc", "links": {"self": {"href": "https://bitbucket.org/!api/2.0/users/%7Bae407617-c9cf-4a54-8331-558d752e3e40%7D"}, "avatar": {"href": "https://secure.gravatar.com/avatar/907a3660d76cf8f995fdd4baa3182d5f?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FMP-5.png"}, "html": {"href": "https://bitbucket.org/%7Bae407617-c9cf-4a54-8331-558d752e3e40%7D/"}}, "type": "user", "uuid": "{ae407617-c9cf-4a54-8331-558d752e3e40}", "account_id": "557058:b7eaa9ff-df3e-4168-8911-79b73835f3be", "nickname": "Michal Pryc"}}, "message": "Initial commit", "summary": {"type": "rendered", "raw": "Initial commit", "markup": "markdown", "html": "<p>Initial commit</p>"}, "links": {"self": {"href": "https://bitbucket.org/!api/2.0/repositories/michalpryc/pelorus-bitbucket/commit/e2c4ef00468dfc10aad1bd2d4c9d470160a7f471"}, "html": {"href": "https://bitbucket.org/michalpryc/pelorus-bitbucket/commits/e2c4ef00468dfc10aad1bd2d4c9d470160a7f471"}, "diff": {"href": "https://bitbucket.org/!api/2.0/repositories/michalpryc/pelorus-bitbucket/diff/e2c4ef00468dfc10aad1bd2d4c9d470160a7f471"}, "approve": {"href": "https://bitbucket.org/!api/2.0/repositories/michalpryc/pelorus-bitbucket/commit/e2c4ef00468dfc10aad1bd2d4c9d470160a7f471/approve"}, "comments": {"href": "https://bitbucket.org/!api/2.0/repositories/michalpryc/pelorus-bitbucket/commit/e2c4ef00468dfc10aad1bd2d4c9d470160a7f471/comments"}, "statuses": {"href": "https://bitbucket.org/!api/2.0/repositories/michalpryc/pelorus-bitbucket/commit/e2c4ef00468dfc10aad1bd2d4c9d470160a7f471/statuses"}, "patch": {"href": "https://bitbucket.org/!api/2.0/repositories/michalpryc/pelorus-bitbucket/patch/e2c4ef00468dfc10aad1bd2d4c9d470160a7f471"}}, "parents": [], "rendered": {"message": {"type": "rendered", "raw": "Initial commit", "markup": "markdown", "html": "<p>Initial commit</p>"}}, "repository": {"type": "repository", "full_name": "michalpryc/pelorus-bitbucket", "links": {"self": {"href": "https://bitbucket.org/!api/2.0/repositories/michalpryc/pelorus-bitbucket"}, "html": {"href": "https://bitbucket.org/michalpryc/pelorus-bitbucket"}, "avatar": {"href": "https://bytebucket.org/ravatar/%7B41109750-2ab2-4daa-922f-0d6fb8b1aa7e%7D?ts=python"}}, "name": "pelorus-bitbucket", "uuid": "{41109750-2ab2-4daa-922f-0d6fb8b1aa7e}"}, "participants": []}
08-03-2022 13:49:17 DEBUG    /home/migi/Development/Konveyor/Pelorus/pelorus-minio/exporters/committime/collector_bitbucket.py:72 get_commit_time() API v2 returned sha: e2c4ef00468dfc10aad1bd2d4c9d470160a7f471, commit date: 2022-07-14T13:46:54+00:00
08-03-2022 13:49:17 DEBUG    /home/migi/Development/Konveyor/Pelorus/pelorus-minio/exporters/committime/collector_base.py:204 get_metrics_from_apps() Adding metric for app bitbucket-binary
08-03-2022 13:49:17 INFO     Collected commit_timestamp{ namespace=bitbucket-binary, app=bitbucket-binary, commit=e2c4ef00468dfc10aad1bd2d4c9d470160a7f471, image_sha=sha256:0edccdcadcfcd59ee4f18e38a67c0a10bac082f9e690e5a2bb24ebdb7efd305b } 1657806414.0
```
