### ISSUE TITLE
Commit time exporter failing on the build referencing git URL ending with "/"

### ISSUE THREAD

**Issue by mpryc** [konveyor/pelorus#590]
While running e2e tests with gitea enabled:

```
(.venv) [migi@fedora pelorus-minio]$ python exporters/committime/app.py
/home/migi/Development/Konveyor/Pelorus/pelorus-minio/exporters/committime/app.py:4: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.util import strtobool
Running committime exporter. No version information found.
Initializing Logger with LogLevel: DEBUG
08-03-2022 12:32:27 ERROR    load cache error: ResourceList.__init__() got an unexpected keyword argument 'base_resource_lookup'
08-03-2022 12:32:27 INFO     =====Using Gitea Collector=====
08-03-2022 12:32:27 INFO     Watching namespaces: ['gitea-binary']
08-03-2022 12:32:27 DEBUG    /home/migi/Development/Konveyor/Pelorus/pelorus-minio/exporters/committime/collector_base.py:123 generate_metrics() Searching for builds with label: app.kubernetes.io/name in namespace: gitea-binary
08-03-2022 12:32:28 DEBUG    /home/migi/Development/Konveyor/Pelorus/pelorus-minio/exporters/committime/collector_base.py:183 get_metrics_from_apps() Repo URL for app gitea-binary is currently None
08-03-2022 12:32:28 DEBUG    /home/migi/Development/Konveyor/Pelorus/pelorus-minio/exporters/committime/__init__.py:100 __parse_repourl() repo url = https://try.gitea.io/mpryc/pelorus-gitea/
08-03-2022 12:32:28 DEBUG    /home/migi/Development/Konveyor/Pelorus/pelorus-minio/exporters/committime/__init__.py:104 __parse_repourl() Parsed: Parsed(pathname='', protocols=['https'], protocol='ssh', href='https://try.gitea.io/mpryc/pelorus-gitea/', resource='pelorus-gitea', user=None, port=None, name=None, owner=None)
08-03-2022 12:32:28 DEBUG    /home/migi/Development/Konveyor/Pelorus/pelorus-minio/exporters/committime/collector_base.py:289 _set_repo_url() Repo URL for build gitea-binary-1 provided by 'io.openshift.build.source-location' annotation: https://try.gitea.io/mpryc/pelorus-gitea/
08-03-2022 12:32:28 DEBUG    /home/migi/Development/Konveyor/Pelorus/pelorus-minio/exporters/committime/collector_base.py:253 _set_commit_hash_from_annotations() Commit hash for build gitea-binary-1 provided by 'io.openshift.build.commit.id' annotation: 897f5c490442e88cc609c241da880128ad02e42b
08-03-2022 12:32:28 DEBUG    /home/migi/Development/Konveyor/Pelorus/pelorus-minio/exporters/committime/collector_base.py:344 _set_commit_timestamp() sha: 897f5c490442e88cc609c241da880128ad02e42b, commit_timestamp not found in cache, executing API call.
08-03-2022 12:32:28 ERROR    Error encountered while getting CommitMetric info:
08-03-2022 12:32:28 ERROR    can only concatenate str (not "NoneType") to str
Traceback (most recent call last):
  File "/home/migi/Development/Konveyor/Pelorus/pelorus-minio/exporters/committime/collector_base.py", line 215, in get_metric_from_build
    metric = self._set_commit_timestamp(metric, errors)
  File "/home/migi/Development/Konveyor/Pelorus/pelorus-minio/exporters/committime/collector_base.py", line 348, in _set_commit_timestamp
    metric = self.get_commit_time(metric)
  File "/home/migi/Development/Konveyor/Pelorus/pelorus-minio/exporters/committime/collector_gitea.py", line 54, in get_commit_time
    self._prefix
TypeError: can only concatenate str (not "NoneType") to str
```

Steps to reproduce (ensure KUBECONFIG is set):

```
build_ns="gitea-binary"
BINARY_BUILDS_NAMESPACES+=("${build_ns}")
build_uri="https://try.gitea.io/mpryc/pelorus-gitea/"
build_hash="897f5c490442e88cc609c241da880128ad02e42b"

./scripts/e2e-tests-templates/build_binary_app -n "${build_ns}" -b "${build_ns}" -u "${build_uri}" -s "${build_hash}"

export LOG_LEVEL=debug
export GIT_PROVIDER=gitea
export NAMESPACES=gitea-binary

python exporters/committime/app.py
```

**Comment by mpryc** [comment]
Note: Same traceback is also in the gitlab backend.

**Comment by mpryc** [comment]
Looks like git url parse function is not correct:

```
(pdb) print(self._CommitMetric__repo_url)
https://try.gitea.io/mpryc/pelorus-gitea/
```
```
parsed = giturlparse.parse(self.__repo_url)

Parsed(pathname='', protocols=['https'], protocol='ssh', href='https://try.gitea.io/mpryc/pelorus-gitea/', resource='pelorus-gitea', user=None, port=None, name=None, owner=None)

```

**Comment by mpryc** [comment]
We need to remove "/" from the url, see:

```
>>> url="https://try.gitea.io/mpryc/pelorus-gitea/"
>>> from giturlparse import parse
>>> parse(url)
Parsed(pathname='', protocols=['https'], protocol='ssh', href='https://try.gitea.io/mpryc/pelorus-gitea/', resource='pelorus-gitea', user=None, port=None, name=None, owner=None)
>>> url=url.strip("/")
>>> parse(url)
Parsed(pathname='/mpryc/pelorus-gitea', protocols=['https'], protocol='https', href='https://try.gitea.io/mpryc/pelorus-gitea', resource='try.gitea.io', user=None, port=None, name='pelorus-gitea', owner='mpryc')
```

**Comment by KevinMGranger** [comment]
Related to #307
