### ISSUE TITLE
Image provider is broken if missing annotation

### ISSUE THREAD

**Issue by mpryc** [konveyor/pelorus#620]
If only name is provided within label and no `io.openshift.build.commit.date` annotation commit time exporter fails with traceback

```
Labels:		app.kubernetes.io/name=basic-python-tekton
Annotations:	image.openshift.io/dockerLayersOrder=ascending
		        image.openshift.io/manifestBlobStored=true
		        io.openshift.build.commit.id=4d8b322346c119fd297388c2e8498b166c5f24f5
		        io.openshift.build.source-location=https://github.com/mpryc/pelorus
		        openshift.io/image.managed=true
```
Traceback:
```
09-02-2022 14:24:16 ERROR    Cannot collect metrics from image: sha256:fef82428f8e941ffe812814480bddba74114ff786113181f2b030400c1311429
Traceback (most recent call last):
  File "/home/migi/Development/Konveyor/Pelorus/pelorus-minio/exporters/committime/app.py", line 174, in <module>
    REGISTRY.register(collector)
  File "/home/migi/Development/Konveyor/Pelorus/pelorus-minio/.venv/lib64/python3.10/site-packages/prometheus_client/registry.py", line 40, in register
    names = self._get_names(collector)
  File "/home/migi/Development/Konveyor/Pelorus/pelorus-minio/.venv/lib64/python3.10/site-packages/prometheus_client/registry.py", line 80, in _get_names
    for metric in desc_func():
  File "/home/migi/Development/Konveyor/Pelorus/pelorus-minio/exporters/committime/collector_base.py", line 87, in collect
    commit_metrics = self.generate_metrics()
  File "/home/migi/Development/Konveyor/Pelorus/pelorus-minio/exporters/committime/collector_image.py", line 173, in generate_metrics
    metrics += self._get_metrics_by_apps_from_images(images_by_app)
  File "/home/migi/Development/Konveyor/Pelorus/pelorus-minio/exporters/committime/collector_image.py", line 186, in _get_metrics_by_apps_from_images
    metric = self.commit_metric_from_image(app, image, errors)
  File "/home/migi/Development/Konveyor/Pelorus/pelorus-minio/exporters/committime/collector_image.py", line 107, in commit_metric_from_image
    metric = self._set_commit_time_from_annotations(metric, errors)
  File "/home/migi/Development/Konveyor/Pelorus/pelorus-minio/exporters/committime/collector_image.py", line 140, in _set_commit_time_from_annotations
    commit_time = metric.annotations.get(commit_time_annotation).strip()

```

**Comment by mpryc** [comment]
Invalid as it's part of PR not the actual master code.
